title: Default Page
move: true
columns:
  maincol:
    width: 2/3
    fields:
      hero:
        label: Hero Image
        type: files
        multiple: false
      introduction:
        required: true
        type: textarea
        buttons:
          - italic
          - link
      blocks:
        label: Story
        type: blocks
        fieldsets: 
          - text
          - quote-custom
          - image
          - video
          - gallery
          - letter
          - audio
          - form-signup
        uploads: false
  sidebar:
    width: 1/3
    sections:
      files:
        label: All Files On This Page
        type: files
